### PR TITLE
Email share button

### PR DESCRIPTION
**Pull request by briandaviddavidson**
This PR adds a `Share via e-mail` button. It allows the developer to pass in whatever `body`, `subject`, `title`, and `recipient` they want. If none are provided, the default e-mail client for that person's computer will open to a blank e-mail.

There is an issue where the button doesn't align properly with the other buttons in the dummy app, so any help would be greatly appreciated @Crabar!

### CODE REVIEW

**Comment by Crabar** [comment]
Thank you for your work. I don't see any bad in a giving to developer a possibility to show "mailto" button with this addon. 

I'm not sure about adding extra parameters such as `body` and `subject`. Component already has `text` and `title` properties that can be used here. And there is a misunderstanding of `title` property in your PR. This property shows a title of share message not a tooltip for `a` component.

**Comment by briandaviddavidson** [comment]
That makes sense. I can change it to just take `body`, `subject`, and `recipients`.

**Comment by Crabar** [comment]
Finally, I had time to look. Really there is some foggy problem with e-mail button positioning. I will try to fix it, and also will make few changes in e-mail button api.

**Comment by briandaviddavidson** [comment]
Closing in favor of #21

**Pull request closed without merging**
