### PR TITLE
Bump `@fortawesome/ember-fontawesome` version

### PR DESCRIPTION
**Pull request by gilest**
In the latest [0.2.2](https://github.com/FortAwesome/ember-fontawesome/releases/tag/0.2.2) version of `@fortawesome/ember-fontawesome`:

> Removed usage of getWithDefault()

I've pinned this version in a project with yarn resolutions and it seems to work fine... 🤷

### CODE REVIEW

**Comment by gilest** [comment]
@Crabar @renaekathleen 👋

**Review by YaroslavPoliakov — APPROVED** [review]

**Review by Crabar — APPROVED** [review]

**Comment by gilest** [comment]
Would it be possible to merge and release this? 
 🥺
👉👈

**Comment by gilest** [comment]
👋  Bump

**Comment by gilest** [comment]
@Crabar could you take a look 👀  at this?

**Comment by gilest** [comment]
Thank you 🙇

**Pull request merged**
