### PR TITLE
Switch all the icons over to SVG logos

### PR DESCRIPTION
**Pull request by briandaviddavidson**
Thanks for putting this together @Crabar! I went in and made all the icons svg based so the fill can be changed. I also simplified down the CSS a bit. I'm happy to make any changes you see. Thanks!

### CODE REVIEW

**Comment by Crabar** [comment]
Thank you very much for your contribution!
I will look this PR asap.

**Comment by Crabar** [comment]
I have checked locally and there is a few problems with css. Could you look it? You can run _ember s_ on your branch and look at test example on _localhost:4200_. It has a bit broken view comparing to https://crabar.github.io/ember-social-share/.

**Comment by briandaviddavidson** [comment]
Sure thing. I did notice when I first submitted that some things looked off, but I couldn't put my finger on it, so having another set of eyes is 💯

I'll try to put changes in today or tomorrow! Thanks @Crabar

**Comment by briandaviddavidson** [comment]
@Crabar I've updated things to make the code cleaner and simplify the CSS some. Let me know if you have any questions 👍

**Comment by Crabar** [comment]
Thank you a lot. I will do some minor style changes and then deploy a new version with your PR included.

**Comment by Crabar** [comment]
Hi there!
What the difference between https://github.com/martndemus/ember-font-awesome and https://github.com/FortAwesome/ember-fontawesome (last one you have used here)?

And I have issues with this plugin in my own project:
"Compile Error: fa-icon is not a helper".

Do you have any clue why it doesn't work?

**Comment by briandaviddavidson** [comment]
Thanks for merging this! I couldn't get the martndemus one to work, but I know the FortAwesome one is the official plugin for Font Awesome.

Which one did you install?

**Comment by Crabar** [comment]
Last one. Btw did you try ember-social-share v0.3.2 in some real app already?

**Comment by briandaviddavidson** [comment]
Hmm. I'm not sure why you'd be getting that error. I know this is from the first repo, but maybe it'll solve the problem? https://github.com/martndemus/ember-font-awesome/issues/99 No, I haven't tried yet in an app, but I am hoping to soon!

**Pull request merged**
